#!/usr/bin/env bash
set -Eeuo pipefail

# =============================================================================
# linux-verify-pendrive-integrity.sh
#
# Purpose
# -------
# Verify, on Linux, the authenticity of the report files generated by the main
# pendrive-preparation script, and verify the integrity of a pendrive by
# recalculating its whole-device hashes and comparing them against the signed
# hash report.
#
# What this script needs
# ----------------------
# 1. The pendrive block device, for example:
#      /dev/sdb
#
# 2. The directory containing:
#      - the report files generated by the main script
#      - the detached GPG signatures (*.asc)
#
# 3. The public key file used to sign those reports, for example:
#      publickey.asc
#
# Typical usage
# -------------
#   sudo ./verify-pendrive-integrity.sh /dev/sdb ./working_dir ./publickey.asc
#
# What this script does
# ---------------------
# 1. Creates a temporary isolated GPG home
# 2. Imports the provided public key
# 3. Verifies all detached signatures (*.asc) found in the report directory
# 4. Identifies the device hash report among the verified reports
# 5. Parses the expected SHA-256, SHA-512, and BLAKE2b values from that report
# 6. Reads the entire block device and recalculates:
#      - SHA-256
#      - SHA-512
#      - BLAKE2b-512
# 7. Compares the calculated values against the signed expected values
# 8. Prints a clear, structured verification report on screen
#
# Security model
# --------------
# This script verifies:
#   - authenticity and integrity of the report files via GPG
#   - integrity of the whole pendrive content via full-device hashes
#
# This script does NOT:
#   - recreate or repair damaged media
#   - verify the GRUB password settings
#   - verify bootability beyond hash equality
#
# =============================================================================
# Dependencies
# =============================================================================
#
# Required commands used directly by this script:
#
#   bash
#   gpg
#   dd
#   sha256sum
#   sha512sum
#   b2sum
#   lsblk
#   blockdev
#   awk
#   sed
#   grep
#   find
#   mktemp
#   readlink
#
# Optional but useful:
#
#   udevadm
#   fdisk
#   blkid
#   dmesg
#
# Debian / Ubuntu / Linux Mint
# ----------------------------
# Install with:
#
#   sudo apt update && sudo apt install -y \
#     gnupg coreutils util-linux findutils gawk sed grep fdisk
#
# Arch Linux
# ----------
# Install with:
#
#   sudo pacman -Syu --needed \
#     gnupg coreutils util-linux findutils gawk sed grep fdisk
#
# RHEL / CentOS / Rocky / AlmaLinux
# ---------------------------------
# Install with:
#
#   sudo dnf install -y \
#     gnupg2 coreutils util-linux findutils gawk sed grep fdisk
#
# Older yum-based systems:
#
#   sudo yum install -y \
#     gnupg2 coreutils util-linux findutils gawk sed grep fdisk
#
# openSUSE
# --------
# Install with:
#
#   sudo zypper install -y \
#     gpg2 coreutils util-linux findutils gawk sed grep fdisk
#
# Notes
# -----
# - Package names can vary slightly across releases and repositories,
#   especially on RPM-based systems and openSUSE.
# - The commands above cover the tools actually used by this verifier script.
#
# =============================================================================

usage() {
    cat <<'EOF'
Usage:
  sudo ./linux-verify-pendrive-integrity.sh DEVICE REPORT_DIR PUBLIC_KEY

Arguments:
  DEVICE      Whole block device to verify, for example /dev/sdb
  REPORT_DIR  Directory containing the generated reports and *.asc signatures
  PUBLIC_KEY  ASCII-armored public key used to sign the reports

Example:
  sudo ./verify-pendrive-integrity.sh /dev/sdb ./working_dir ./publickey.asc

Expected files in REPORT_DIR:
  - one or more report files
  - detached signatures for those files, with extension .asc
  - among them, a whole-device hash report containing:
      SHA-256:
      SHA-512:
      BLAKE2b:

Exit codes:
  0  success
  1  usage or dependency error
  2  signature verification problems
  3  device hash mismatch
  4  device I/O error while hashing
EOF
}

die() {
    echo "ERROR: $*" >&2
    exit 1
}

need_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

have_cmd() {
    command -v "$1" >/dev/null 2>&1
}

color_setup() {
    if [[ -t 1 ]]; then
        C_RESET=$'\033[0m'
        C_BOLD=$'\033[1m'
        C_DIM=$'\033[2m'
        C_RED=$'\033[31m'
        C_GREEN=$'\033[32m'
        C_YELLOW=$'\033[33m'
        C_BLUE=$'\033[34m'
        C_CYAN=$'\033[36m'
    else
        C_RESET=""
        C_BOLD=""
        C_DIM=""
        C_RED=""
        C_GREEN=""
        C_YELLOW=""
        C_BLUE=""
        C_CYAN=""
    fi
}

hr() {
    printf '%*s\n' "${COLUMNS:-100}" '' | tr ' ' '─'
}

section() {
    echo
    hr
    printf "%b%s%b\n" "$C_BOLD$C_CYAN" "$*" "$C_RESET"
    hr
}

subsection() {
    echo
    printf "%b%s%b\n" "$C_BOLD$C_BLUE" "$*" "$C_RESET"
    hr
}

ok() {
    printf "%b✔ %s%b\n" "$C_GREEN$C_BOLD" "$*" "$C_RESET"
}

warn() {
    printf "%b⚠ %s%b\n" "$C_YELLOW$C_BOLD" "$*" "$C_RESET"
}

failmsg() {
    printf "%b✘ %s%b\n" "$C_RED$C_BOLD" "$*" "$C_RESET"
}

info() {
    printf "%b• %s%b\n" "$C_BLUE" "$*" "$C_RESET"
}

trim() {
    sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
}

extract_pubkey_fingerprint() {
    local keyfile="$1"
    gpg --show-keys --with-colons "$keyfile" 2>/dev/null | awk -F: '/^fpr:/ {print $10; exit}'
}

extract_pubkey_uid() {
    local keyfile="$1"
    gpg --show-keys --with-colons "$keyfile" 2>/dev/null | awk -F: '/^uid:/ {print $10; exit}'
}

verify_signature_file() {
    local sig="$1"
    local target="$2"

    local out signer created
    out="$(gpg --homedir "$GNUPGHOME" --status-fd 1 --verify "$sig" "$target" 2>&1 || true)"

    if grep -q '^\[GNUPG:\] GOODSIG ' <<< "$out" && grep -q '^\[GNUPG:\] VALIDSIG ' <<< "$out"; then
        signer="$(awk '/^\[GNUPG:\] GOODSIG / {sub(/^\[GNUPG:\] GOODSIG [^ ]+ /,""); print; exit}' <<< "$out" | trim)"
        created="$(awk '/^\[GNUPG:\] VALIDSIG / {print $4; exit}' <<< "$out")"
        VERIFY_RESULT="GOOD"
        VERIFY_SIGNER="${signer:-unknown}"
        VERIFY_CREATED="${created:-unknown}"
        VERIFY_MESSAGE=""
        return 0
    fi

    if grep -q '^\[GNUPG:\] BADSIG ' <<< "$out"; then
        signer="$(awk '/^\[GNUPG:\] BADSIG / {sub(/^\[GNUPG:\] BADSIG [^ ]+ /,""); print; exit}' <<< "$out" | trim)"
        VERIFY_RESULT="BAD"
        VERIFY_SIGNER="${signer:-unknown}"
        VERIFY_CREATED=""
        VERIFY_MESSAGE="Invalid signature or modified file"
        return 1
    fi

    if grep -q 'No public key' <<< "$out" || grep -q '^\[GNUPG:\] NO_PUBKEY ' <<< "$out"; then
        VERIFY_RESULT="NO_PUBKEY"
        VERIFY_SIGNER=""
        VERIFY_CREATED=""
        VERIFY_MESSAGE="Public key not available in temporary keyring"
        return 1
    fi

    if grep -qi 'No such file' <<< "$out" || grep -qi 'can.t open' <<< "$out"; then
        VERIFY_RESULT="MISSING"
        VERIFY_SIGNER=""
        VERIFY_CREATED=""
        VERIFY_MESSAGE="Signed file not found"
        return 1
    fi

    VERIFY_RESULT="UNKNOWN"
    VERIFY_SIGNER=""
    VERIFY_CREATED=""
    VERIFY_MESSAGE="$(tail -n 3 <<< "$out" | tr '\n' ' ' | trim)"
    return 1
}

find_hash_report() {
    local dir="$1"

    # First preference: conventional name
    if [[ -f "$dir/$(basename "$DEVICE").hash-report.txt" ]]; then
        printf '%s\n' "$dir/$(basename "$DEVICE").hash-report.txt"
        return 0
    fi

    # Second preference: any file matching *hash-report.txt
    local found=""
    while IFS= read -r -d '' f; do
        found="$f"
        break
    done < <(find "$dir" -maxdepth 1 -type f -name '*hash-report.txt' -print0 | sort -z)

    if [[ -n "$found" ]]; then
        printf '%s\n' "$found"
        return 0
    fi

    # Third preference: content-based detection
    while IFS= read -r -d '' f; do
        if grep -q 'WHOLE-DEVICE CRYPTOGRAPHIC HASH REPORT' "$f" 2>/dev/null; then
            printf '%s\n' "$f"
            return 0
        fi
    done < <(find "$dir" -maxdepth 1 -type f ! -name '*.asc' -print0)

    return 1
}

parse_expected_hashes() {
    local report="$1"

    EXPECTED_SHA256="$(awk -F': *' '/^SHA-256:/ {print $2; exit}' "$report" | trim)"
    EXPECTED_SHA512="$(awk -F': *' '/^SHA-512:/ {print $2; exit}' "$report" | trim)"
    EXPECTED_BLAKE2B="$(awk -F': *' '/^BLAKE2b:/ {print $2; exit}' "$report" | trim)"

    [[ -n "$EXPECTED_SHA256" ]] || die "Could not parse SHA-256 from hash report: $report"
    [[ -n "$EXPECTED_SHA512" ]] || die "Could not parse SHA-512 from hash report: $report"
    [[ -n "$EXPECTED_BLAKE2B" ]] || die "Could not parse BLAKE2b from hash report: $report"
}

compute_device_hash() {
    local algorithm="$1"
    local dev="$2"

    case "$algorithm" in
        sha256)
            dd if="$dev" bs=16M iflag=fullblock status=progress 2>"$TMPDIR/dd.sha256.log" | sha256sum | awk '{print $1}'
            ;;
        sha512)
            dd if="$dev" bs=16M iflag=fullblock status=progress 2>"$TMPDIR/dd.sha512.log" | sha512sum | awk '{print $1}'
            ;;
        blake2b)
            dd if="$dev" bs=16M iflag=fullblock status=progress 2>"$TMPDIR/dd.blake2b.log" | b2sum | awk '{print $1}'
            ;;
        *)
            die "Unknown algorithm: $algorithm"
            ;;
    esac
}

summarize_device() {
    local dev="$1"
    info "Device: $dev"
    info "Resolved path: $(readlink -f "$dev")"
    info "Kernel-reported size: $(blockdev --getsize64 "$dev") bytes"
    echo
    lsblk -b -o NAME,SIZE,MODEL,VENDOR,SERIAL,TRAN "$dev" || true
    echo
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

[[ $# -ne 3 ]] && usage && exit 1

DEVICE="$1"
REPORT_DIR="$(readlink -f "$2")"
PUBLIC_KEY="$(readlink -f "$3")"

[[ -b "$DEVICE" ]] || die "Not a block device: $DEVICE"
[[ -d "$REPORT_DIR" ]] || die "Report directory not found: $REPORT_DIR"
[[ -f "$PUBLIC_KEY" ]] || die "Public key file not found: $PUBLIC_KEY"
[[ $EUID -eq 0 ]] || die "Run as root or with sudo, because reading the whole block device requires elevated privileges"

case "$DEVICE" in
    /dev/sd[a-z]|/dev/sd[a-z][a-z]|/dev/nvme[0-9]n[0-9]|/dev/mmcblk[0-9])
        ;;
    *)
        die "Refusing unusual device path: $DEVICE"
        ;;
esac

need_cmd gpg
need_cmd dd
need_cmd sha256sum
need_cmd sha512sum
need_cmd b2sum
need_cmd lsblk
need_cmd blockdev
need_cmd awk
need_cmd sed
need_cmd grep
need_cmd find
need_cmd mktemp
need_cmd readlink

color_setup

GNUPGHOME="$(mktemp -d)"
TMPDIR="$(mktemp -d)"
cleanup() {
    rm -rf "$GNUPGHOME" "$TMPDIR"
}
trap cleanup EXIT
chmod 700 "$GNUPGHOME"

section "PENDRIVE INTEGRITY VERIFICATION"

info "Public key: $PUBLIC_KEY"
info "Report directory: $REPORT_DIR"
info "Target device: $DEVICE"

subsection "Public key import"
KEY_IMPORT_OUT="$(gpg --homedir "$GNUPGHOME" --import "$PUBLIC_KEY" 2>&1 || true)"
if ! grep -qiE 'imported|unchanged' <<< "$KEY_IMPORT_OUT"; then
    echo "$KEY_IMPORT_OUT"
    die "Failed to import public key"
fi

PUBKEY_UID="$(extract_pubkey_uid "$PUBLIC_KEY")"
PUBKEY_FPR="$(extract_pubkey_fingerprint "$PUBLIC_KEY")"

ok "Public key imported into temporary isolated keyring"
printf "%b%-16s%b %s\n" "$C_BOLD" "Key UID:" "$C_RESET" "${PUBKEY_UID:-unknown}"
printf "%b%-16s%b %s\n" "$C_BOLD" "Fingerprint:" "$C_RESET" "${PUBKEY_FPR:-unknown}"

subsection "Device summary"
summarize_device "$DEVICE"

subsection "Verifying signed report files"
mapfile -t SIG_FILES < <(find "$REPORT_DIR" -maxdepth 1 -type f -name '*.asc' | sort)

if [[ ${#SIG_FILES[@]} -eq 0 ]]; then
    failmsg "No detached signatures (*.asc) were found in $REPORT_DIR"
    exit 2
fi

TOTAL_SIGS=0
GOOD_SIGS=0
BAD_SIGS=0
MISSING_SIGS=0
OTHER_SIGS=0

printf "%b%-42s %-12s %-30s %-20s%b\n" \
    "$C_BOLD" "File" "Status" "Signer" "Signature time" "$C_RESET"
hr

for sig in "${SIG_FILES[@]}"; do
    TOTAL_SIGS=$((TOTAL_SIGS + 1))
    target="${sig%.asc}"
    base="$(basename "$target")"

    if [[ ! -f "$target" ]]; then
        MISSING_SIGS=$((MISSING_SIGS + 1))
        printf "%-42s %b%-12s%b %-30s %-20s\n" \
            "$base" "$C_YELLOW" "MISSING" "$C_RESET" "-" "-"
        continue
    fi

    if verify_signature_file "$sig" "$target"; then
        GOOD_SIGS=$((GOOD_SIGS + 1))
        printf "%-42s %b%-12s%b %-30s %-20s\n" \
            "$base" "$C_GREEN" "VALID" "$C_RESET" "${VERIFY_SIGNER:0:30}" "$VERIFY_CREATED"
    else
        case "$VERIFY_RESULT" in
            BAD)
                BAD_SIGS=$((BAD_SIGS + 1))
                printf "%-42s %b%-12s%b %-30s %-20s\n" \
                    "$base" "$C_RED" "INVALID" "$C_RESET" "${VERIFY_SIGNER:0:30}" "-"
                ;;
            MISSING)
                MISSING_SIGS=$((MISSING_SIGS + 1))
                printf "%-42s %b%-12s%b %-30s %-20s\n" \
                    "$base" "$C_YELLOW" "MISSING" "$C_RESET" "-" "-"
                ;;
            *)
                OTHER_SIGS=$((OTHER_SIGS + 1))
                printf "%-42s %b%-12s%b %-30s %-20s\n" \
                    "$base" "$C_YELLOW" "UNDEFINED" "$C_RESET" "-" "-"
                ;;
        esac
    fi
done

echo
printf "%b%-24s%b %d\n" "$C_BOLD" "Total signatures:" "$C_RESET" "$TOTAL_SIGS"
printf "%b%-24s%b %b%d%b\n" "$C_BOLD" "Valid signatures:" "$C_RESET" "$C_GREEN" "$GOOD_SIGS" "$C_RESET"
printf "%b%-24s%b %b%d%b\n" "$C_BOLD" "Invalid signatures:" "$C_RESET" "$C_RED" "$BAD_SIGS" "$C_RESET"
printf "%b%-24s%b %b%d%b\n" "$C_BOLD" "Missing signed files:" "$C_RESET" "$C_YELLOW" "$MISSING_SIGS" "$C_RESET"
printf "%b%-24s%b %b%d%b\n" "$C_BOLD" "Other problems:" "$C_RESET" "$C_YELLOW" "$OTHER_SIGS" "$C_RESET"

if (( BAD_SIGS > 0 || MISSING_SIGS > 0 || OTHER_SIGS > 0 )); then
    echo
    failmsg "One or more report signatures failed verification"
    exit 2
fi

ok "All report signatures are valid"

subsection "Locating whole-device hash report"
HASH_REPORT="$(find_hash_report "$REPORT_DIR" || true)"
[[ -n "${HASH_REPORT:-}" ]] || die "Could not find the whole-device hash report inside $REPORT_DIR"

ok "Hash report found: $HASH_REPORT"

parse_expected_hashes "$HASH_REPORT"

printf "%b%-16s%b %s\n" "$C_BOLD" "Expected SHA-256:" "$C_RESET" "$EXPECTED_SHA256"
printf "%b%-16s%b %s\n" "$C_BOLD" "Expected SHA-512:" "$C_RESET" "$EXPECTED_SHA512"
printf "%b%-16s%b %s\n" "$C_BOLD" "Expected BLAKE2b:" "$C_RESET" "$EXPECTED_BLAKE2B"

subsection "Computing whole-device hashes"
info "This reads the entire block device three times and may take a while"

echo
echo "Calculating SHA-256..."
ACTUAL_SHA256="$(compute_device_hash sha256 "$DEVICE")" || {
    failmsg "I/O error while computing SHA-256"
    exit 4
}

echo
echo "Calculating SHA-512..."
ACTUAL_SHA512="$(compute_device_hash sha512 "$DEVICE")" || {
    failmsg "I/O error while computing SHA-512"
    exit 4
}

echo
echo "Calculating BLAKE2b-512..."
ACTUAL_BLAKE2B="$(compute_device_hash blake2b "$DEVICE")" || {
    failmsg "I/O error while computing BLAKE2b"
    exit 4
}

subsection "Comparing expected and actual values"
printf "%b%-12s %-128s %-128s %-10s%b\n" \
    "$C_BOLD" "Algorithm" "Expected" "Actual" "Result" "$C_RESET"
hr

MISMATCH=0

compare_line() {
    local name="$1"
    local expected="$2"
    local actual="$3"

    if [[ "$expected" == "$actual" ]]; then
        printf "%-12s %-128s %-128s %b%-10s%b\n" \
            "$name" "$expected" "$actual" "$C_GREEN" "MATCH" "$C_RESET"
    else
        printf "%-12s %-128s %-128s %b%-10s%b\n" \
            "$name" "$expected" "$actual" "$C_RED" "MISMATCH" "$C_RESET"
        MISMATCH=1
    fi
}

compare_line "SHA-256" "$EXPECTED_SHA256" "$ACTUAL_SHA256"
compare_line "SHA-512" "$EXPECTED_SHA512" "$ACTUAL_SHA512"
compare_line "BLAKE2b" "$EXPECTED_BLAKE2B" "$ACTUAL_BLAKE2B"

section "FINAL RESULT"

if (( MISMATCH == 0 )); then
    ok "All whole-device hashes match the signed report"
    ok "The pendrive content is consistent with the authenticated integrity report"
    exit 0
else
    failmsg "The device hashes do not match the signed report"
    failmsg "The pendrive must be considered modified, corrupted, or not the original verified device"
    exit 3
fi