<#
===============================================================================
verify-pendrive-integrity.ps1
===============================================================================

Purpose
-------
Verify, on Windows, the authenticity of the report files generated by the main
pendrive-preparation script, and verify the integrity of a pendrive by
recalculating its whole-device hashes and comparing them against the signed
hash report.

What this script needs
----------------------
1. The pendrive physical device, for example:
     \\.\PhysicalDrive2
   or simply:
     2

2. The directory containing:
     - the report files generated by the main script
     - the detached GPG signatures (*.asc)

3. The public key file used to sign those reports, for example:
     publickey.asc

Typical usage
-------------
  .\verify-pendrive-integrity.ps1 -Device 2 -ReportDir .\working_dir -PublicKey .\publickey.asc

or

  .\verify-pendrive-integrity.ps1 -Device \\.\PhysicalDrive2 -ReportDir .\working_dir -PublicKey .\publickey.asc

What this script does
---------------------
1. Validates the arguments and checks that it is running as Administrator
2. Creates a temporary isolated GPG home
3. Imports the provided public key
4. Verifies all detached signatures (*.asc) found in the report directory
5. Identifies the whole-device hash report among the verified reports
6. Parses the expected SHA-256, SHA-512, and BLAKE2b values from that report
7. Reads the entire physical device and recalculates:
     - SHA-256
     - SHA-512
     - BLAKE2b-512
8. Compares the calculated values against the signed expected values
9. Prints a clear, structured verification report on screen

Security model
--------------
This script verifies:
  - authenticity and integrity of the report files via GPG
  - integrity of the whole pendrive content via full-device hashes

This script does NOT:
  - recreate or repair damaged media
  - verify the GRUB password settings
  - verify bootability beyond hash equality

===============================================================================
Dependencies
===============================================================================

Required
--------
- PowerShell 5.1 or newer
- Administrator privileges
- Gpg4win (for gpg.exe)
- Python 3 (used to read the raw physical drive and compute hashes)

Why Python is required
----------------------
Windows does not provide a simple native command-line path to hash a whole raw
physical drive with SHA-256, SHA-512, and BLAKE2b in one portable way. This
script uses Python's hashlib to compute all three hashes directly from the
device stream.

Install on Windows with Winget
------------------------------
Open PowerShell as Administrator and run:

  winget install -e --id GnuPG.Gpg4win
  winget install -e --id Python.Python.3.9

If you prefer a newer Python package ID on your system, adjust accordingly.

Manual installation
-------------------
- Gpg4win: https://www.gpg4win.org/download.html
- Python:   https://www.python.org/downloads/windows/

Verification of dependencies
----------------------------
The following commands must work in a fresh PowerShell session:

  gpg --version
  python --version

Execution policy
----------------
If Windows blocks local scripts, run once in an elevated PowerShell:

  Set-ExecutionPolicy -Scope CurrentUser RemoteSigned

Then execute this script again.

Examples
--------
  .\verify-pendrive-integrity.ps1 -Device 2 -ReportDir .\working_dir -PublicKey .\publickey.asc

  .\verify-pendrive-integrity.ps1 -Device \\.\PhysicalDrive2 -ReportDir C:\reports -PublicKey C:\keys\publickey.asc

Exit codes
----------
  0  success
  1  usage or dependency error
  2  signature verification problems
  3  device hash mismatch
  4  device I/O error while hashing

===============================================================================
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$Device,

    [Parameter(Mandatory = $true)]
    [string]$ReportDir,

    [Parameter(Mandatory = $true)]
    [string]$PublicKey
)

$ErrorActionPreference = "Stop"

function Write-HR {
    Write-Host ("─" * 100)
}

function Write-Section {
    param([string]$Title)
    Write-Host ""
    Write-HR
    Write-Host $Title -ForegroundColor Cyan
    Write-HR
}

function Write-Subsection {
    param([string]$Title)
    Write-Host ""
    Write-Host $Title -ForegroundColor Blue
    Write-HR
}

function Write-Ok {
    param([string]$Message)
    Write-Host "✔ $Message" -ForegroundColor Green
}

function Write-WarnMsg {
    param([string]$Message)
    Write-Host "⚠ $Message" -ForegroundColor Yellow
}

function Write-FailMsg {
    param([string]$Message)
    Write-Host "✘ $Message" -ForegroundColor Red
}

function Write-Info {
    param([string]$Message)
    Write-Host "• $Message" -ForegroundColor DarkCyan
}

function Test-Administrator {
    $identity  = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = [Security.Principal.WindowsPrincipal]::new($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Require-Command {
    param([string]$Name)
    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
        throw "Missing required command: $Name"
    }
}

function Normalize-DevicePath {
    param([string]$Value)

    if ($Value -match '^[0-9]+$') {
        return "\\.\PhysicalDrive$Value"
    }

    if ($Value -match '^PhysicalDrive([0-9]+)$') {
        return "\\.\$Value"
    }

    if ($Value -match '^\\\\\.\\PhysicalDrive[0-9]+$') {
        return $Value
    }

    throw "Invalid device format. Use a disk number like 2 or a path like \\.\PhysicalDrive2"
}

function Get-PhysicalDriveNumber {
    param([string]$DevicePath)

    if ($DevicePath -match 'PhysicalDrive([0-9]+)$') {
        return [int]$Matches[1]
    }

    throw "Could not parse disk number from device path: $DevicePath"
}

function Convert-PathSafe {
    param([string]$PathValue)
    return (Resolve-Path -LiteralPath $PathValue).Path
}

function Get-PublicKeyFingerprint {
    param([string]$KeyFile)

    $out = & gpg --show-keys --with-colons $KeyFile 2>$null
    if (-not $out) { return $null }

    foreach ($line in $out) {
        if ($line -like 'fpr:*') {
            $parts = $line -split ':'
            if ($parts.Length -ge 10) { return $parts[9] }
        }
    }
    return $null
}

function Get-PublicKeyUid {
    param([string]$KeyFile)

    $out = & gpg --show-keys --with-colons $KeyFile 2>$null
    if (-not $out) { return $null }

    foreach ($line in $out) {
        if ($line -like 'uid:*') {
            $parts = $line -split ':'
            if ($parts.Length -ge 10) { return $parts[9] }
        }
    }
    return $null
}

function Verify-SignatureFile {
    param(
        [string]$GpgHome,
        [string]$SigFile,
        [string]$TargetFile
    )

    $output = & gpg --homedir $GpgHome --status-fd 1 --verify $SigFile $TargetFile 2>&1
    $text   = ($output -join "`n")

    $result = [ordered]@{
        Status      = "UNKNOWN"
        Signer      = ""
        Created     = ""
        Message     = ""
    }

    if ($text -match '^\[GNUPG:\] GOODSIG ' -and $text -match '^\[GNUPG:\] VALIDSIG ') {
        $goodSigLine  = ($output | Where-Object { $_ -match '^\[GNUPG:\] GOODSIG ' } | Select-Object -First 1)
        $validSigLine = ($output | Where-Object { $_ -match '^\[GNUPG:\] VALIDSIG ' } | Select-Object -First 1)

        if ($goodSigLine) {
            $result.Signer = ($goodSigLine -replace '^\[GNUPG:\] GOODSIG [^ ]+ ', '').Trim()
        }
        if ($validSigLine) {
            $parts = $validSigLine -split ' '
            if ($parts.Length -ge 5) {
                $result.Created = $parts[4]
            }
        }

        $result.Status = "VALID"
        return [pscustomobject]$result
    }

    if ($text -match '^\[GNUPG:\] BADSIG ') {
        $badSigLine = ($output | Where-Object { $_ -match '^\[GNUPG:\] BADSIG ' } | Select-Object -First 1)
        if ($badSigLine) {
            $result.Signer = ($badSigLine -replace '^\[GNUPG:\] BADSIG [^ ]+ ', '').Trim()
        }
        $result.Status  = "INVALID"
        $result.Message = "Invalid signature or modified file"
        return [pscustomobject]$result
    }

    if ($text -match 'No public key' -or $text -match '^\[GNUPG:\] NO_PUBKEY ') {
        $result.Status  = "NO_PUBKEY"
        $result.Message = "Public key not available in temporary keyring"
        return [pscustomobject]$result
    }

    if (-not (Test-Path -LiteralPath $TargetFile)) {
        $result.Status  = "MISSING"
        $result.Message = "Signed file not found"
        return [pscustomobject]$result
    }

    $result.Status  = "UNDEFINED"
    $result.Message = (($output | Select-Object -Last 3) -join " ").Trim()
    return [pscustomobject]$result
}

function Find-HashReport {
    param(
        [string]$Directory,
        [string]$DevicePath
    )

    $baseName = Split-Path -Path $DevicePath -Leaf
    $candidate = Join-Path $Directory "$baseName.hash-report.txt"
    if (Test-Path -LiteralPath $candidate) {
        return $candidate
    }

    $report = Get-ChildItem -LiteralPath $Directory -File -Filter "*hash-report.txt" | Select-Object -First 1
    if ($report) { return $report.FullName }

    $files = Get-ChildItem -LiteralPath $Directory -File | Where-Object { $_.Extension -ne ".asc" }
    foreach ($file in $files) {
        try {
            $content = Get-Content -LiteralPath $file.FullName -Raw -ErrorAction Stop
            if ($content -match 'WHOLE-DEVICE CRYPTOGRAPHIC HASH REPORT') {
                return $file.FullName
            }
        } catch {
        }
    }

    return $null
}

function Parse-ExpectedHashes {
    param([string]$ReportFile)

    $content = Get-Content -LiteralPath $ReportFile -Raw

    $sha256 = [regex]::Match($content, '(?m)^SHA-256:\s*([0-9a-fA-F]+)\s*$')
    $sha512 = [regex]::Match($content, '(?m)^SHA-512:\s*([0-9a-fA-F]+)\s*$')
    $blake2 = [regex]::Match($content, '(?m)^BLAKE2b:\s*([0-9a-fA-F]+)\s*$')

    if (-not $sha256.Success) { throw "Could not parse SHA-256 from report: $ReportFile" }
    if (-not $sha512.Success) { throw "Could not parse SHA-512 from report: $ReportFile" }
    if (-not $blake2.Success) { throw "Could not parse BLAKE2b from report: $ReportFile" }

    return [pscustomobject]@{
        SHA256 = $sha256.Groups[1].Value.ToLowerInvariant()
        SHA512 = $sha512.Groups[1].Value.ToLowerInvariant()
        BLAKE2 = $blake2.Groups[1].Value.ToLowerInvariant()
    }
}

function Get-DiskSummary {
    param([int]$DiskNumber)

    $disk = Get-Disk -Number $DiskNumber -ErrorAction Stop
    return $disk
}

function Compute-DeviceHashesWithPython {
    param(
        [string]$DevicePath,
        [string]$TempDir
    )

    $pyFile   = Join-Path $TempDir "compute_hashes.py"
    $jsonFile = Join-Path $TempDir "hashes.json"

    $pySource = @'
import hashlib
import json
import os
import sys

device = sys.argv[1]
outfile = sys.argv[2]

sha256 = hashlib.sha256()
sha512 = hashlib.sha512()
blake2 = hashlib.blake2b()

bufsize = 16 * 1024 * 1024
total = 0

try:
    with open(device, "rb", buffering=0) as f:
        while True:
            chunk = f.read(bufsize)
            if not chunk:
                break
            sha256.update(chunk)
            sha512.update(chunk)
            blake2.update(chunk)
            total += len(chunk)
            print(f"Read {total} bytes", flush=True)
except Exception as e:
    print(f"PYTHON_DEVICE_READ_ERROR: {e}", file=sys.stderr)
    sys.exit(4)

result = {
    "sha256": sha256.hexdigest(),
    "sha512": sha512.hexdigest(),
    "blake2b": blake2.hexdigest(),
    "bytes_read": total
}

with open(outfile, "w", encoding="utf-8") as out:
    json.dump(result, out)
'@

    Set-Content -LiteralPath $pyFile -Value $pySource -Encoding UTF8

    & python $pyFile $DevicePath $jsonFile
    $exitCode = $LASTEXITCODE
    if ($exitCode -ne 0) {
        throw "Python device hashing failed with exit code $exitCode"
    }

    if (-not (Test-Path -LiteralPath $jsonFile)) {
        throw "Python hashing did not produce the expected JSON result"
    }

    $obj = Get-Content -LiteralPath $jsonFile -Raw | ConvertFrom-Json
    return [pscustomobject]@{
        SHA256   = $obj.sha256.ToLowerInvariant()
        SHA512   = $obj.sha512.ToLowerInvariant()
        BLAKE2   = $obj.blake2b.ToLowerInvariant()
        BytesRead = [Int64]$obj.bytes_read
    }
}

# -----------------------------------------------------------------------------
# Validation and setup
# -----------------------------------------------------------------------------

try {
    $Device    = Normalize-DevicePath -Value $Device
    $ReportDir = Convert-PathSafe -PathValue $ReportDir
    $PublicKey = Convert-PathSafe -PathValue $PublicKey
} catch {
    Write-Error $_
    usage
    exit 1
}

if (-not (Test-Path -LiteralPath $ReportDir -PathType Container)) {
    Write-Error "Report directory not found: $ReportDir"
    exit 1
}

if (-not (Test-Path -LiteralPath $PublicKey -PathType Leaf)) {
    Write-Error "Public key file not found: $PublicKey"
    exit 1
}

if (-not (Test-Administrator)) {
    Write-Error "This script must be run as Administrator"
    exit 1
}

try {
    Require-Command -Name "gpg"
    Require-Command -Name "python"
} catch {
    Write-Error $_
    exit 1
}

$GpgHome = Join-Path ([System.IO.Path]::GetTempPath()) ("gpg-home-" + [guid]::NewGuid().ToString())
$TempDir = Join-Path ([System.IO.Path]::GetTempPath()) ("pendrive-verify-" + [guid]::NewGuid().ToString())

New-Item -ItemType Directory -Path $GpgHome | Out-Null
New-Item -ItemType Directory -Path $TempDir  | Out-Null

try {
    color_setup

    $DiskNumber = Get-PhysicalDriveNumber -DevicePath $Device
    $DiskInfo   = Get-DiskSummary -DiskNumber $DiskNumber

    Write-Section "PENDRIVE INTEGRITY VERIFICATION"

    Write-Info "Public key: $PublicKey"
    Write-Info "Report directory: $ReportDir"
    Write-Info "Target device: $Device"

    Write-Subsection "Public key import"
    $importOut = & gpg --homedir $GpgHome --import $PublicKey 2>&1
    if (-not (($importOut -join "`n") -match 'imported|unchanged')) {
        throw "Failed to import public key"
    }

    $PubKeyUid = Get-PublicKeyUid -KeyFile $PublicKey
    $PubKeyFpr = Get-PublicKeyFingerprint -KeyFile $PublicKey

    Write-Ok "Public key imported into temporary isolated keyring"
    Write-Host ("{0,-16} {1}" -f "Key UID:", $PubKeyUid)
    Write-Host ("{0,-16} {1}" -f "Fingerprint:", $PubKeyFpr)

    Write-Subsection "Device summary"
    Write-Info "Disk number: $DiskNumber"
    Write-Info "Friendly name: $($DiskInfo.FriendlyName)"
    Write-Info "Bus type: $($DiskInfo.BusType)"
    Write-Info "Health status: $($DiskInfo.HealthStatus)"
    Write-Info "Operational status: $($DiskInfo.OperationalStatus)"
    Write-Info "Size: $($DiskInfo.Size) bytes"
    Write-Host ""

    Get-Disk -Number $DiskNumber |
        Select-Object Number, FriendlyName, SerialNumber, BusType, PartitionStyle, HealthStatus, OperationalStatus, Size |
        Format-Table -AutoSize

    Write-Host ""
    Get-Partition -DiskNumber $DiskNumber -ErrorAction SilentlyContinue | Format-Table -AutoSize

    Write-Subsection "Verifying signed report files"
    $sigFiles = Get-ChildItem -LiteralPath $ReportDir -File -Filter "*.asc" | Sort-Object Name
    if (-not $sigFiles -or $sigFiles.Count -eq 0) {
        Write-FailMsg "No detached signatures (*.asc) were found in $ReportDir"
        exit 2
    }

    $totalSigs   = 0
    $goodSigs    = 0
    $badSigs     = 0
    $missingSigs = 0
    $otherSigs   = 0

    "{0,-42} {1,-12} {2,-30} {3,-20}" -f "File", "Status", "Signer", "Signature time"
    Write-HR

    foreach ($sig in $sigFiles) {
        $totalSigs++
        $target = $sig.FullName -replace '\.asc$', ''
        $base   = [System.IO.Path]::GetFileName($target)

        if (-not (Test-Path -LiteralPath $target)) {
            $missingSigs++
            "{0,-42} {1,-12} {2,-30} {3,-20}" -f $base, "MISSING", "-", "-"
            continue
        }

        $vr = Verify-SignatureFile -GpgHome $GpgHome -SigFile $sig.FullName -TargetFile $target

        switch ($vr.Status) {
            "VALID" {
                $goodSigs++
                "{0,-42} {1,-12} {2,-30} {3,-20}" -f $base, "VALID", $vr.Signer.Substring(0, [Math]::Min(30, $vr.Signer.Length)), $vr.Created
            }
            "INVALID" {
                $badSigs++
                "{0,-42} {1,-12} {2,-30} {3,-20}" -f $base, "INVALID", $vr.Signer.Substring(0, [Math]::Min(30, $vr.Signer.Length)), "-"
            }
            "MISSING" {
                $missingSigs++
                "{0,-42} {1,-12} {2,-30} {3,-20}" -f $base, "MISSING", "-", "-"
            }
            default {
                $otherSigs++
                "{0,-42} {1,-12} {2,-30} {3,-20}" -f $base, "UNDEFINED", "-", "-"
            }
        }
    }

    Write-Host ""
    Write-Host ("{0,-24} {1}" -f "Total signatures:", $totalSigs)
    Write-Host ("{0,-24} {1}" -f "Valid signatures:", $goodSigs)
    Write-Host ("{0,-24} {1}" -f "Invalid signatures:", $badSigs)
    Write-Host ("{0,-24} {1}" -f "Missing signed files:", $missingSigs)
    Write-Host ("{0,-24} {1}" -f "Other problems:", $otherSigs)

    if ($badSigs -gt 0 -or $missingSigs -gt 0 -or $otherSigs -gt 0) {
        Write-FailMsg "One or more report signatures failed verification"
        exit 2
    }

    Write-Ok "All report signatures are valid"

    Write-Subsection "Locating whole-device hash report"
    $hashReport = Find-HashReport -Directory $ReportDir -DevicePath $Device
    if (-not $hashReport) {
        throw "Could not find the whole-device hash report inside $ReportDir"
    }

    Write-Ok "Hash report found: $hashReport"

    $expected = Parse-ExpectedHashes -ReportFile $hashReport

    Write-Host ("{0,-18} {1}" -f "Expected SHA-256:", $expected.SHA256)
    Write-Host ("{0,-18} {1}" -f "Expected SHA-512:", $expected.SHA512)
    Write-Host ("{0,-18} {1}" -f "Expected BLAKE2b:", $expected.BLAKE2)

    Write-Subsection "Computing whole-device hashes"
    Write-Info "This reads the entire physical drive and may take a while"
    $actual = Compute-DeviceHashesWithPython -DevicePath $Device -TempDir $TempDir

    Write-Subsection "Comparing expected and actual values"
    "{0,-12} {1,-128} {2,-128} {3,-10}" -f "Algorithm", "Expected", "Actual", "Result"
    Write-HR

    $mismatch = $false

    function Show-CompareLine {
        param(
            [string]$Name,
            [string]$Expected,
            [string]$Actual
        )
        if ($Expected -eq $Actual) {
            "{0,-12} {1,-128} {2,-128} {3,-10}" -f $Name, $Expected, $Actual, "MATCH"
        } else {
            $script:mismatch = $true
            "{0,-12} {1,-128} {2,-128} {3,-10}" -f $Name, $Expected, $Actual, "MISMATCH"
        }
    }

    Show-CompareLine -Name "SHA-256" -Expected $expected.SHA256 -Actual $actual.SHA256
    Show-CompareLine -Name "SHA-512" -Expected $expected.SHA512 -Actual $actual.SHA512
    Show-CompareLine -Name "BLAKE2b" -Expected $expected.BLAKE2 -Actual $actual.BLAKE2

    Write-Section "FINAL RESULT"

    if (-not $mismatch) {
        Write-Ok "All whole-device hashes match the signed report"
        Write-Ok "The pendrive content is consistent with the authenticated integrity report"
        exit 0
    } else {
        Write-FailMsg "The device hashes do not match the signed report"
        Write-FailMsg "The pendrive must be considered modified, corrupted, or not the original verified device"
        exit 3
    }
}
catch {
    $msg = $_.Exception.Message
    if ($msg -match 'Python device hashing failed' -or $msg -match 'PYTHON_DEVICE_READ_ERROR') {
        Write-FailMsg "Device I/O error while hashing the physical drive"
        Write-Host $msg
        exit 4
    } else {
        Write-FailMsg $msg
        exit 1
    }
}
finally {
    if (Test-Path -LiteralPath $GpgHome) {
        Remove-Item -LiteralPath $GpgHome -Recurse -Force -ErrorAction SilentlyContinue
    }
    if (Test-Path -LiteralPath $TempDir) {
        Remove-Item -LiteralPath $TempDir -Recurse -Force -ErrorAction SilentlyContinue
    }
}